### ISSUE TITLE
Better error response on missing parameter

### ISSUE THREAD

**Issue by yeya** [cloudwm/cloudcli#23]
**When running this command:**
`#cloudcli server info <SERVER_ID>`

**The expected response should be:**
`info command failed: Failed to run command method (serversInfo), missing server id` or anything similar.

**The actual response is:**
`info command failed: Failed to run command method (serversInfo)`

I missed the `--id` flag, but could not understand why the command failed.

**Comment by OriHoch** [comment]
thanks, it was fixed in last release
