### ISSUE TITLE
add to the “cloudcli server info” the billing cycle and the pricing of the servers.

### ISSUE THREAD

**Issue by ddark-il** [cloudwm/cloudcli#33]
add to the “cloudcli server info” the billing cycle and the pricing of the servers.
 
The pricing will show both monthly price, hourly powered on and hourly powered off pricing (3 prices).

**Comment by OriHoch** [comment]
fixed and deployed in [cloudcli-server v1.0.1](https://github.com/cloudwm/cloudcli-server/releases/tag/v1.0.1)

no need to update the binary, just run `cloudcli init` to update
